on:
  push:
    tags:
      - "v*"
jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends build-essential

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-gnu x86_64-pc-windows-gnu

      - name: Build the executable
        run: cargo build --release --target x86_64-unknown-linux-gnu --target x86_64-pc-windows-gnu

      - name: Tar x86_64 binary
        run: tar -czvf yufmath-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release yufmath

      - name: Zip windows binary
        run: zip -j yufmath-windows.zip target/x86_64-pc-windows-gnu/release/yufmath.exe

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 yufmath-gnu-linux-x86_64.tar.gz > yufmath-gnu-linux-x86_64.tar.gz.sha256
          shasum -a 256 yufmath-windows.zip > yufmath-windows.zip.sha256

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: '["yufmath-gnu-linux-x86_64.tar.gz", "yufmath-windows.zip", "yufmath-gnu-linux-x86_64.tar.gz.sha256", "yufmath-windows.zip.sha256"]'

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build the executable
        run: cargo build --release --target x86_64-apple-darwin --target aarch64-apple-darwin

      - name: Tar binary 1
        run: tar -czvf yufmath-apple-darwin-x86_64.tar.gz -C target/x86_64-apple-darwin/release yufmath

      - name: Tar binary 2
        run: tar -czvf yufmath-apple-darwin-aarch64.tar.gz -C target/aarch64-apple-darwin/release yufmath

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 yufmath-apple-darwin-x86_64.tar.gz > yufmath-apple-darwin-x86_64.tar.gz.sha256
          shasum -a 256 yufmath-apple-darwin-aarch64.tar.gz > yufmath-apple-darwin-aarch64.tar.gz.sha256

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: '["yufmath-apple-darwin-x86_64.tar.gz", "yufmath-apple-darwin-aarch64.tar.gz", "yufmath-apple-darwin-x86_64.tar.gz.sha256", "yufmath-apple-darwin-aarch64.tar.gz.sha256"]'

  crates:
    runs-on: ubuntu-latest
    needs: [linux_windows, macos]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
